### ISSUE TITLE
Gadget Optimization

### ISSUE THREAD

**Issue by lazovicff** [eigen-trust/eigen-trust#76]
We should strictly define how many columns and rows our circuits should have so that the network should run optimally.

We are building a distributed system with decentralized control - this is directly correlated with the performance requirements for our node to run - the lighter the node, the more computers can run it (preferably unnoticed - without taking too much resources) which results in more managers, which results in more decentralization.

Based on our new protocol (#75), the node will do 15 iterations (15 proofs) once a day for a single peer. Each manager should manage minimum of 10 peers. 10 * 15 = 150 proofs.

Benchmarks to compare to:
CPU: M1 Pro
Proving time: 300ms
Rows: 512
150 proofs time: 300 * 150 = 4500ms = 45s

Task:
We should aim to have a fixed amount of columns that will be reused in multiple gates. The number of columns we should have should be minimal needed to fit into 512 rows.
- [x] Make a Common gadget that reuses the same columns for `and`, `is_boolean`, `is_equal`, `is_zero`, `mul`, `select` -- these are all one-row gadgets
    - Proposal: A Common gadget should have 3 columns and 6 selector (each for different kind of a gate)
    - Gadgets `sum`, `bits2num`, `lt_eq`, `set`, should have a separate configs
- [x] Optimize `eddsa` gadget - use less columns + combine with Common gadget
    - 7 common columns for eddsa + Bits2Num config + 3 selector (for `add`,  `into_affine` and `scalar_mul`)
- [x] Optimize `poseidon` and`poseidon_sponge` gadget - use less columns
    - Dont put mds matrix into fixed columns - use `Expression::Const`, since the mds values are the same in every row
    - Reuse `poseidon` state columns inside `poseidon_sponge`

**Comment by 4rmanc** [comment]
This test [gadget](https://github.com/4rmanc/eigen-trust/blob/master/circuit/src/gadgets/region_test.rs) shows that when we assign 4 columns for two different gates and call both of them in one test, the region will only use 2 rows in total by cycling between the selectors.

**Comment by lazovicff** [comment]
PRs for each of the tasks:
Common Gadget Optimization - https://github.com/eigen-trust/eigen-trust/pull/104
Eddsa Gadget Optimization - https://github.com/eigen-trust/eigen-trust/pull/106
Poseidon Optimization - https://github.com/eigen-trust/eigen-trust/pull/108
