### ISSUE TITLE
Gadget Testing

### ISSUE THREAD

**Issue by lazovicff** [eigen-trust/eigen-trust#77]
- [x] Test `accumulate/sum` gadget
    - Rename to Sum
    - Test case: Zero element array
    - Test case: Large arrays with random values
    - Add inline docs
- [x] Test `and` gadget
    - Test case: x = 0, y = 0
    - Test case: x = 0, y = 1
    - Test case: x = 1, y = 1
    - Test case: x = 1, y =0
    - Add inline docs
- [x] Test `bits2num` gadget
    - Test case: Use zero value
    - Test case: Biggest value of the field
    - Test case: Biggest field value + 1 should wrap around the field, but pass
    - Add inline docs
- [x] Test `is_boolean` gadget
    - Test case: Use 1 as value
    - Test case: Use value larger than 1
    - Add inline docs
- [x] Test `is_equal` gadget
    - Test case: Use two non-equal values
    - Add inline docs
- [x] Test `is_zero` gadget
    - Test case: Use non-zero value
    - Add inline docs
- [x] Test `lt_eq` gadget
    - Test case: Use x smaller than y
    - Test case: Use largest 252-bit number for x, small y
    - Test case: Use largest 252-bit number for y, small x
    - Test case: Use largest 252-bit number for both x and y
    - Test case: Use equal numbers
    - Add inline docs
- [x] Test `mul` gadget
    - Test case: Use 0 as y
    - Test case: Use 1 as y
    - Add inline docs
- [x] Test `select` gadget
    - Test case: Use 1 as a bit
    - Test case: Use higher than 1 as a bit
    - Add inline docs
- [x] Test `set` gadget
    - Test case: Use target that is not in the set
    - Test case: Use 0 as a target
    - Test case: Use big sets: >512 elements
- [x] `poseidon` gadget
    - Add Inline docs
- [x] Test `eddsa` gadget
    - ScalarMul - Test Case: Use 0 as a scalar
    - ScalarMul - Test Case: Use 1 as a scalar
    - Eddsa - Test case: Use invalid R
    - Eddsa - Test case: Use invalid s
    - Eddsa - Test case: Use invalid Public Key
    - Eddsa - Test case: Use invalid message
    - Add - Inline docs
    - IntoAffine - Inline docs
    - ScalarMul - Inline docs
    - Eddsa - Inline docs

**Comment by 4rmanc** [comment]
@lazovicff At the bits2num gadget testing task. One of them states that I should use zero value. Does that mean zero as a value or zero elements to the input? Because the [new](https://github.com/lazovicff/eigen-trust/blob/master/circuit/src/gadgets/bits2num.rs#L31) function in that circuit expects at least one argument.

**Comment by lazovicff** [comment]
@4rmanc  `0` as a value should be used, which means that [`new`](https://github.com/lazovicff/eigen-trust/blob/master/circuit/src/gadgets/bits2num.rs#L31) should receive:
1. `value` - and assigned cell holding value 0
2. `bits` - empty array (0-len array)

**Comment by lazovicff** [comment]
List of PRs:
https://github.com/eigen-trust/eigen-trust/pull/81
https://github.com/eigen-trust/eigen-trust/pull/82
https://github.com/eigen-trust/eigen-trust/pull/83
https://github.com/eigen-trust/eigen-trust/pull/85
https://github.com/eigen-trust/eigen-trust/pull/86
https://github.com/eigen-trust/eigen-trust/pull/87
https://github.com/eigen-trust/eigen-trust/pull/88
https://github.com/eigen-trust/eigen-trust/pull/90
https://github.com/eigen-trust/eigen-trust/pull/91
https://github.com/eigen-trust/eigen-trust/pull/92
https://github.com/eigen-trust/eigen-trust/pull/93
https://github.com/eigen-trust/eigen-trust/pull/100
