### ISSUE TITLE
Merkle Tree construction and membership proofs

### ISSUE THREAD

**Issue by lazovicff** [eigen-trust/eigen-trust#94]
This task consists of 2 gadgets:

Native Merkle Tree implementation
- [x] Construction of the whole tree from array
- [x] Construction of membership path at specific index

Gadgets Merkle tree implementation:
- [x] Verification of membership given the path

**Comment by lazovicff** [comment]
Given an array of leaves -- the array length will be 2 ** H, where H is height of the tree. E.g: H = 9, array length = 2 ** 9 = 512
1. Construct the whole binary merkle tree from this array, by hashing the pairs of 2. -- (0, 1), (2, 3), ..., (510, 511)
2. Costruct the membership path - given the index or leaf value, find the pair, and re-construct the root hash, but along the way, save the path values into the path_arr.

**Comment by 4rmanc** [comment]
Merkle Tree native and circuit implementation - #123
